[package]
name = "service-transport"
version = "0.1.0"
edition = "2021"
license = "MIT"

[features]
default = ["transport_mock"]
transport_mock = []
transport_http = []
transport_ble = []

[dependencies]
service-core = { path = "../core" }
